- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(df0f9628-9472-4ce6-bff5-74c20bfbc0c7)'
    appType: 'webApp'
    WebAppName: 'hello'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'